### ISSUE TITLE
Stops with error message

### ISSUE THREAD

**Issue by AlexanderLill** [spyhunter99/nexusCloner#1]
a@b ~/Downloads/nexusCloner-master » java -jar target/nexusCloner-1.0-SNAPSHOT-jar-with-dependencies.jar -url https://HOSTNAME/\#browse/browse:REPONAME -download          1 ↵

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.kryo.util.UnsafeUtil (file:/fghj/nexusCloner-1.0-SNAPSHOT-jar-with-dependencies.jar) to constructor java.nio.DirectByteBuffer(long,int,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.util.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.io.FileNotFoundException: index.bin (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:220)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:158)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:113)
	at org.miloss.nexuscloner.Main.main(Main.java:226)

**Comment by AlexanderLill** [comment]
Ah I need to execute `-index` first

@spyhunter99 which format should the URLs have?

**Comment by spyhunter99** [comment]
hmmm good question. IIRC, point it at the top level. So if you have a nexus instance, it would be the top level of the repo to clone. Something like
http://yourhost/content/my_repo_releases/

where by your artifacts would be something like
http://yourhost/content/my_repo_releases/com/github/blah/coolpackage-1.0.0.jar
http://yourhost/content/my_repo_releases/com/github/blah/coolpackage-1.0.0.pom
etc

at least that's what i remember, it's been a while

**Comment by spyhunter99** [comment]
fixed, thanks for the bug report
